### ISSUE TITLE
Suggestion: Add a player comparision feature

### ISSUE THREAD

**Issue by refeax** [ddnet/ddnet-web#233]
I came to this idea due to having no direct way to see which same maps a player didn't finish as me so it would be easier to find a map to play together. The feature could act like a "filter" in the player profile page where you could write the player name of the player you would like to compare maps to and it shows all mutually unfinished maps. This feature could even be extended to compare certain details which eachother, like finish time etc.
Let me know if this idea sounds absurd or not

**Comment by bencie** [comment]
This already exists on ddnet.org/players/yourname (top right corner, Compare button)
Example: https://ddnet.org/compare/bencie/spur/

**Comment by refeax** [comment]
I must be blind then. Does that feature also tell you which mutually unfinished maps you have?

**Comment by bencie** [comment]
It shows you which maps are finished by either one of you. Maps unfinished by neither player will be shown collapsed, the same way a normal player profile works

**Comment by refeax** [comment]
Seems like my suggestion is useless then. Thanks for the answer!
