### ISSUE TITLE
Adding release date to map on website

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet-web#87]
Title says it all, it would be nice to have the release date of maps on the website.

**Comment by trafilaw** [comment]
Is this not already the release date?
https://i.imgur.com/sZQKVsg.png

Or do I understand your suggestion wrong?

**Comment by Chairn** [comment]
I guess, it's missing only on the rank page:
![image](https://user-images.githubusercontent.com/10178629/83355297-f02dad00-a35e-11ea-84b7-f5f41c4bf48a.png)

**Comment by def-** [comment]
> Maybe we could also show the rank date?

This is shown by hovering over the time.

**Comment by Chairn** [comment]
Ok for hovering, didn't know that.

But release date is missing everywhere actually:
![image](https://user-images.githubusercontent.com/10178629/83450050-dd959f80-a454-11ea-82e2-8c3544c8a57e.png)
Tried hovering every element, and no release date appear.

Firefox 76.0.1 64 bits on Windows 10.

**Comment by Ekidoxx** [comment]
@def- he meant map release date, not date & time when the rank was made (though that one is nice)

**Comment by Ekidoxx** [comment]
If you guys don't mind, I'd like to try doing it.
Will most likely ask for (some) help anyway, or eventually just give up, but well... yea ^^

**Comment by def-** [comment]
Done, should be online in ~1 hour.
