### ISSUE TITLE
Localized times in Javascript

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet-web#94]
local times on ddnet website for ranks/tournament pages with javascript? not so easy with DST: https://stackoverflow.com/questions/10087819/convert-date-to-another-timezone-in-javascript

I would prefer to have this in pure JS. Maybe someone wants to take a look

**Comment by Learath2** [comment]
I think this would end up being a rather massive dataset with all the tz oddities around the world. Maybe we should do this on the server and perform a small ajax request to get the tournament time?

**Comment by def-** [comment]
I hoped browsers have a way to convert unix timestamp to local time. I want this on /ranks/ too.

**Comment by Learath2** [comment]
[Date.prototype.toLocaleTimeString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString) looks like it'd work actually

**Comment by edg-l** [comment]
Maybe you can wrap all the generates dates you find in a span with a class e.g "date" and have a js script convert the dates.

I took a look at ddnet-scripts ddnet.py and looks a bit messy but may work, or maybe it's a bad solution, some use parts of the date like just the hour, so maybe add more classes like date-hour or stuff to give more control to the script. (this looks like a hacky solution ngl)

**Comment by Learath2** [comment]
Nah, an on document loaded to convert all these sounds like the best way. I
thought there was no way to get a locale specific timestamp

**Comment by edg-l** [comment]
> Nah, an on document loaded to convert all these sounds like the best way. I thought there was no way to get a locale specific timestamp. All we need is a unix timestamp marked with a class

thats kinda what i said O.o
